### ISSUE TITLE
Error syntax in build script

### ISSUE THREAD

**Issue by RosaWagner** [productiontype/NewsReader#8]
```
  File "./tool-vf/fixNameTable.py", line 36
    font_file_full_path = f"{folder}/{filename}"
                                               ^
SyntaxError: invalid syntax
  File "./tool-vf/fixNameTable.py", line 36
    font_file_full_path = f"{folder}/{filename}"
                                               ^
SyntaxError: invalid syntax
Remove unwanted fvar instances
Traceback (most recent call last):
  File "./tool-vf/removeUnwantedVFInstances.py", line 3, in <module>
    from fontbakery.constants import PlatformID, WindowsEncodingID, WindowsLanguageID
ImportError: No module named fontbakery.constants
Remove unwanted fvar instances
Traceback (most recent call last):
  File "./tool-vf/removeUnwantedVFInstances.py", line 3, in <module>
    from fontbakery.constants import PlatformID, WindowsEncodingID, WindowsLanguageID
ImportError: No module named fontbakery.constants
MBP-de-Rosalie:sources rosalie$
```

**Comment by RosaWagner** [comment]
Ok this issue can be avoided by installing a virtual env
